version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=${MONGO_URI_Backend_NODE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - REDIS_URL=${REDIS_URL}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - IMAGE_SERVICE_URL=${IMAGE_SERVICE_URL}
    depends_on:
      - redis
    volumes:
      - ./backend:/usr/src/app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  frontend:
    build: ./frontweb
    ports:
      - "3000:3000"
    volumes:
      - ./frontweb:/usr/src/app
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
      - REACT_APP_FLASK_API_BASE_URL=${REACT_APP_FLASK_API_BASE_URL}

  theme-selector-service:
    build: ./theme-selector-service
    ports:
      - "8001:8001"
    environment:
      - MONGO_URITHEME=${MONGO_URITHEME}
      - CORS_ORIGIN=${CORS_ORIGIN}
    volumes:
      - ./theme-selector-service:/app
    depends_on:
      - redis

volumes:
  mongo-data:
