version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - REDIS_URL=redis://redis:6379
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - IMAGE_SERVICE_URL=${IMAGE_SERVICE_URL}
    depends_on:
      - redis
    volumes:
      - ./backend:/usr/src/app

  image-server:
    build: ./image-server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  nextstepsocket:
    build: ./nextstepsocket
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - mongo

  theme-selector-service:
    build: ./theme-selector-service
    ports:
      - "5001:5001"

  frontweb:
    build: ./frontweb
    ports:
      - "3000:3000"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mongo:
    image: "mongo:4.4"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
