server:
  port: ${SPRING_SERVER_PORT:8081}

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: ${MONGO_URI_SPRING}
  application:
    name: nextstepsocket

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.mychat: DEBUG
